global using Pong.PongNew.Objects;
global using Pong.Core.Window;
global using Pong.Core.Objects;
global using Pong.Core.Game;
global using System.Numerics;
global using Pong.PongNew;
global using static Pong.Core.Loggers.LoggerCore;
global using SDL3;
global using Pong.Core.Inputs;
global using System.Drawing;